HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>AndBang.com</title>

    <!-- Mobile viewport optimization h5bp.com/ad -->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">

    <!-- Mobile IE allows us to activate ClearType technology for smoothing fonts for easy reading -->
    <meta http-equiv="cleartype" content="on">

    <link href="//d13w15pduyzezm.cloudfront.net/assets/application-fe9b95d6070f4a77d84a2ac04d2fc10d.css" media="all" rel="stylesheet" type="text/css" />

    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body class="minimal error_500">
    <div class="layout-content minimal">
      <h5>Portland, we have a problem!</h5>
      <p>
        The And Bang servers seem to be having a problem, if reloading doesn't help please visit <a href="https://status.andbang.com">our status page</a>.
      </p>
      <h5>System Status</h5>
      <p>
        <strong><span id="insert-system-status-here"></span></strong><br>
        If our status page says we're up but something is clearly wrong, <a href="mailto:support@andbang.com">shoot us an email</a> letting us know what you're seeing.
      </p>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
    <!-- must be very last since it relies on dependencies loaded above -->
    <script type="text/javascript" src="//status-page-production.s3.amazonaws.com/se.js"></script>
    <script type="text/javascript">
      window.fetchStatusPage({
        organizationId: '4c08hx0kxz2p',     // required
        renderTo: '#insert-system-status-here',        // optional, will render summary of status
        successCallback: function(data) {   // optional, for full control of data returned
          // do something with the data here
          console.log(data.status.description);
        }
      });
    </script>
  </body>
</html>